### PR TITLE
add link to open all pages found

### PR DESCRIPTION
**Pull request by WardCunningham**
This pull request adds a link » to open the pages found.

I've updated this to version 1.0.0 because it has been stable for some time now.

image

### CODE REVIEW

**Comment by WardCunningham** [comment]
I should explain what problem I am solving with this addition because there are other solutions that have been passed over because they are too big of steps for weekend coding. I conjure @nrn to help consider further work.

I am writing a pattern language that will span maybe a dozen pages. I want to draw a diagram of the complete "knowledge graph" by rolling up the fragments and rendering it with my Graphviz transporter. I thought the Grep plugin could help so I link to it from my list of patterns.

http://best.ward.bay.wiki.org/view/inventory-of-workflow-steps/view/merge-all-graphs

image

One could shift-click each Grep result to achieve the same effect. But our current scrolling behavior makes this tedious. So I mimic the  »  behavior from the Action plugin. [github](https://github.com/fedwiki/wiki-plugin-activity/blob/master/client/activity.coffee#L33-L42)

A better solution might be to extend the page gathering logic in the Transporter to notice a plugin offering a `page-source` and get the pages from it leaving the lineup out of the picture. [github](https://github.com/fedwiki/wiki-plugin-transport/blob/master/client/transport.coffee#L13-L21)

An even better solution would be to somehow query for `all-graphs-in-site` or `all-graphs-in-neighborhood` in some i/o efficient way. We've talked of allowing plugins to annotate the sitemap to support such queries. The specific case then was finding Transporters, not Graphs, but perhaps now with two use cases we should think about this more.

**Comment by WardCunningham** [comment]
I tediously shift-clicked all my Graph pages into the lineup and then Transported them to Graphviz for this result. My goal is to examine this composite graph frequently while writing.

image

I see immediately that my pattern language needs more work since I never intended to have two starting points. When I'm finished with this project I will drag the final composite graph onto some introductory overview page.

**Comment by paul90** [comment]
Published as + wiki-plugin-grep@1.0.0

**Comment by paul90** [comment]
wiki patched to 0.11.4 to update dependencies for this version.

**Comment by WardCunningham** [comment]
Oh, so sweet. I was working on the pattern language in question when I saw the notice of Paul's publication flash in the corner of my screen. I added Grep to my Plugmatic listing for the site, installed the update, and then ran a revised aggregated plot.

image

Tedium gone.

There are still lots of steps involved in authoring a pattern language in wiki. But the steps make sense as elements of a workflow. That's what my pattern language is about.

**Pull request merged**
